import Foundation
import Testing
@testable import BrewBrowserKit

/// Parse tests for the M2 bundle loader. The real `bundles.json` (repo root,
/// generated by scripts/validate-recipes.mjs) is the primary fixture — both
/// shells must load the same first-party bundles. The lossy test proves one malformed
/// recipe is skipped without dropping the valid ones.
@Suite("BundleParsing")
struct BundleParsingTests {

    /// Resolve the repo-root `bundles.json` from this file's location:
    /// native/Tests/BrewBrowserKitTests/BundleParsingTests.swift → up 4 → repo root.
    private static func realBundlesData() throws -> Data {
        let repoRoot = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()   // BrewBrowserKitTests/
            .deletingLastPathComponent()   // Tests/
            .deletingLastPathComponent()   // native/
            .deletingLastPathComponent()   // repo root
        let url = repoRoot.appendingPathComponent("bundles.json")
        guard let data = try? Data(contentsOf: url) else {
            print("bundles.json not found at: \(url.path)")
            throw CocoaError(.fileNoSuchFile)
        }
        return data
    }

    @Test func parsesAllBundles() throws {
        // Bump when adding/removing a first-party recipe under recipes/.
        let bundles = BundleCatalog.parse(try Self.realBundlesData())
        #expect(bundles.count == 9, "expected 9 bundles, got \(bundles.count)")
    }

    @Test func spotCheckAgenticWebDev() throws {
        let bundles = BundleCatalog.parse(try Self.realBundlesData())
        let agentic = try #require(bundles.first { $0.id == "agentic-web-dev" }, "agentic-web-dev bundle missing")

        // The agentic stack must carry the coding agent and version control.
        #expect(agentic.packages.contains { $0.name == "opencode" && $0.kind == "formula" })
        #expect(agentic.packages.contains { $0.name == "git" && $0.kind == "formula" })
    }

    @Test func spotCheckLocalLLM() throws {
        let bundles = BundleCatalog.parse(try Self.realBundlesData())
        let llm = try #require(bundles.first { $0.id == "local-llm" }, "local-llm bundle missing")

        // Two packages: ollama (formula) + open-webui (cask).
        #expect(llm.packages.count == 2)
        #expect(llm.packages.contains { $0.name == "ollama" && $0.kind == "formula" })
        #expect(llm.packages.contains { $0.name == "open-webui" && $0.kind == "cask" })

        // Requires gate (reused M1 BundleRequires).
        #expect(llm.requires?.minRamGB == 8)

        // At least one setup step of kind "service".
        #expect(llm.setup?.contains { $0.kind == "service" } == true)
    }

    /// One malformed recipe (missing the required `id`) must be dropped while the
    /// two valid recipes still parse — the per-element `Throwable` lossy wrapper.
    @Test func lossySkipsMalformed() throws {
        let json = """
        {
          "schemaVersion": 1,
          "bundles": [
            { "id": "good-one", "name": "Good One", "tagline": "fine", "category": "Data",
              "packages": [ { "name": "redis", "kind": "formula" } ] },
            { "name": "No ID", "tagline": "broken — missing id", "category": "Data",
              "packages": [ { "name": "postgresql@16", "kind": "formula" } ] },
            { "id": "good-two", "name": "Good Two", "tagline": "also fine", "category": "Media",
              "packages": [ { "name": "ffmpeg", "kind": "formula" } ] }
          ]
        }
        """
        let bundles = BundleCatalog.parse(Data(json.utf8))
        #expect(bundles.count == 2, "malformed recipe should be skipped, got \(bundles.count)")
        #expect(bundles.map(\.id).sorted() == ["good-one", "good-two"])
    }

    /// Unknown JSON keys are ignored (tolerant Codable) and a recipe with only
    /// the required fields still parses.
    @Test func toleratesUnknownKeysAndMinimalRecipe() throws {
        let json = """
        {
          "bundles": [
            { "id": "minimal", "name": "Minimal", "tagline": "required-only", "category": "Development",
              "packages": [ { "name": "node", "kind": "formula" } ],
              "futureField": { "nested": true }, "another": [1, 2, 3] }
          ]
        }
        """
        let bundles = BundleCatalog.parse(Data(json.utf8))
        #expect(bundles.count == 1)
        #expect(bundles.first?.requires == nil)
        #expect(bundles.first?.setup == nil)
        #expect(bundles.first?.id == "minimal")
    }

    /// All five setup-step kinds decode, each populating the fields the M4 UI
    /// reads. The renderer is hard to unit-test, but the decode contract is what
    /// the checklist depends on.
    @Test func decodesAllFiveSetupStepKinds() throws {
        let json = """
        {
          "bundles": [
            { "id": "all-kinds", "name": "All Kinds", "tagline": "every step kind",
              "category": "Development",
              "packages": [ { "name": "node", "kind": "formula" } ],
              "setup": [
                { "kind": "service", "service": "ollama", "label": "Start Ollama" },
                { "kind": "open", "url": "http://localhost:8080", "label": "Open UI" },
                { "kind": "reveal", "path": "/tmp/models", "label": "Reveal models" },
                { "kind": "command", "run": "ollama pull llama3.2", "label": "Pull a model", "external": true },
                { "kind": "note", "text": "Models are large downloads." }
              ] }
          ]
        }
        """
        let bundles = BundleCatalog.parse(Data(json.utf8))
        let steps = try #require(bundles.first?.setup, "setup should decode")
        #expect(steps.count == 5)
        #expect(steps.map(\.kind) == ["service", "open", "reveal", "command", "note"])
        #expect(steps[0].service == "ollama")
        #expect(steps[1].url == "http://localhost:8080")
        #expect(steps[2].path == "/tmp/models")
        #expect(steps[3].run == "ollama pull llama3.2")
        #expect(steps[3].external == true)
        #expect(steps[4].text == "Models are large downloads.")
    }

    /// Contract guarantee the M4 UI relies on: every `command` step in a shipped
    /// recipe is `external: true` (the app copies it, never runs it). Checked
    /// against the REAL local-llm recipe (`ollama pull llama3.2`).
    @Test func realLocalLLMCommandStepsAreExternal() throws {
        let bundles = BundleCatalog.parse(try Self.realBundlesData())
        let llm = try #require(bundles.first { $0.id == "local-llm" }, "local-llm missing")
        let commands = (llm.setup ?? []).filter { $0.kind == "command" }
        #expect(!commands.isEmpty, "local-llm should have a command setup step")
        for c in commands {
            #expect(c.external == true, "command step '\(c.run ?? "")' must be external:true (contract)")
        }
    }

    // MARK: - Live refresh (M5) parseLive fail-soft contract

    /// A payload whose `schemaVersion` is newer than we support → `nil`, so the
    /// caller keeps the bundled copy rather than mis-parsing an unknown format.
    @Test func parseLiveRefusesNewerSchema() {
        let json = """
        { "schemaVersion": 2, "bundles": [
          { "id": "future", "name": "Future", "tagline": "t", "category": "Data",
            "packages": [ { "name": "redis", "kind": "formula" } ] }
        ] }
        """
        #expect(BundleCatalog.parseLive(Data(json.utf8)) == nil)
    }

    /// A valid same-schema payload → the decoded bundles (the live set replaces
    /// the bundled one).
    @Test func parseLiveAcceptsSupportedSchema() throws {
        let json = """
        { "schemaVersion": 1, "bundles": [
          { "id": "live-a", "name": "Live A", "tagline": "t", "category": "Media",
            "packages": [ { "name": "ffmpeg", "kind": "formula" } ] },
          { "id": "live-b", "name": "Live B", "tagline": "t", "category": "Data",
            "packages": [ { "name": "redis", "kind": "formula" } ] }
        ] }
        """
        let live = try #require(BundleCatalog.parseLive(Data(json.utf8)))
        #expect(live.map(\.id) == ["live-a", "live-b"])
    }

    /// A missing `schemaVersion` is treated as compatible (parses).
    @Test func parseLiveTreatsMissingSchemaAsCompatible() throws {
        let json = """
        { "bundles": [
          { "id": "no-ver", "name": "No Ver", "tagline": "t", "category": "Development",
            "packages": [ { "name": "node", "kind": "formula" } ] }
        ] }
        """
        let live = try #require(BundleCatalog.parseLive(Data(json.utf8)))
        #expect(live.map(\.id) == ["no-ver"])
    }

    /// Malformed top-level JSON → `nil` (keep the bundled copy).
    @Test func parseLiveFallsBackOnMalformed() {
        #expect(BundleCatalog.parseLive(Data("{ not json".utf8)) == nil)
    }

    /// Within a supported-schema payload, a single malformed recipe is still
    /// dropped (lossy), matching the bundled `parse` behavior.
    @Test func parseLiveIsLossyWithinSupportedSchema() throws {
        let json = """
        { "schemaVersion": 1, "bundles": [
          { "id": "ok", "name": "OK", "tagline": "t", "category": "Data",
            "packages": [ { "name": "redis", "kind": "formula" } ] },
          { "name": "no id", "tagline": "broken", "category": "Data",
            "packages": [ { "name": "x", "kind": "formula" } ] }
        ] }
        """
        let live = try #require(BundleCatalog.parseLive(Data(json.utf8)))
        #expect(live.map(\.id) == ["ok"])
    }
}
