import Foundation

/// Bundles (curated "recipes") — a named set of Homebrew packages plus the
/// capability requirements and post-install setup guidance the UI renders. The
/// data contract mirrors the Tauri side (`Bundle`/`BundlePackage`/`SetupStep`
/// in src-tauri/src/types.rs + src/lib/types.ts) and the JSON Schema at
/// recipes/recipe.schema.json. Parsed from the bundled `bundles.json`
/// (generated by scripts/validate-recipes.mjs) at launch by `BundleCatalog`.
///
/// Tolerant by design: every field beyond the required core is optional (missing
/// → nil), unknown JSON keys are ignored by Codable, and a single malformed
/// recipe is skipped rather than failing the whole catalog (see `BundleCatalog`).
///
/// NOTE: named `BrewBundle`, not `Bundle`. A module-level type named `Bundle`
/// would shadow `Foundation.Bundle` — including inside SwiftPM's generated
/// `resource_bundle_accessor.swift`, which references `Bundle.module` unqualified
/// and can't be edited — breaking every bundled-resource lookup in this target.
/// The `Brew*` prefix also matches `BrewService`/`BrewOutputParsing`.
public struct BrewBundle: Sendable, Codable, Identifiable, Hashable {
    /// kebab-case identifier, unique across the catalog (e.g. "local-llm").
    public let id: String
    /// Display name (≤40 chars per the schema).
    public let name: String
    /// One-line pitch (≤90 chars).
    public let tagline: String
    /// Optional 2–4 sentence intent paragraph — the "why/what" of the bundle,
    /// distinct from the short `tagline` and from post-install `caveats`.
    public let description: String?
    /// One of AI / Graphics / Media / Development / Data / Productivity.
    public let category: String
    /// Optional icon token (SF Symbol-ish name the UI maps to a glyph).
    public let icon: String?
    /// The packages this bundle installs (≥1). Formula or cask.
    public let packages: [BundlePackage]
    /// Third-party tap that must be trusted before install, if any.
    public let tap: String?
    /// Host requirements gate (RAM / disk / arch / gpu). Reused M1 type.
    public let requires: BundleRequires?
    /// RAM-tier → capability note, keyed by integer-string GB (e.g. "16").
    public let capabilityNotes: [String: String]?
    /// Ordered post-install steps (start a service, open a URL, run a command…).
    public let setup: [SetupStep]?
    /// Free-text caveats shown before/after install (≤240 chars).
    public let caveats: String?
    /// "Further reading" links (label + https url).
    public let links: [BundleLink]?
    /// Who curates this recipe (e.g. "brew-browser").
    public let maintainer: String?
    /// First app version the recipe shipped in (e.g. "0.7.0").
    public let addedIn: String?

    public init(id: String, name: String, tagline: String, description: String? = nil,
                category: String, icon: String? = nil, packages: [BundlePackage],
                tap: String? = nil, requires: BundleRequires? = nil,
                capabilityNotes: [String: String]? = nil,
                setup: [SetupStep]? = nil, caveats: String? = nil,
                links: [BundleLink]? = nil, maintainer: String? = nil, addedIn: String? = nil) {
        self.id = id
        self.name = name
        self.tagline = tagline
        self.description = description
        self.category = category
        self.icon = icon
        self.packages = packages
        self.tap = tap
        self.requires = requires
        self.capabilityNotes = capabilityNotes
        self.setup = setup
        self.caveats = caveats
        self.links = links
        self.maintainer = maintainer
        self.addedIn = addedIn
    }
}

/// One package inside a bundle. `kind` is "formula" or "cask" (kept as a plain
/// String for tolerant parsing — an unknown kind survives rather than dropping
/// the whole recipe).
public struct BundlePackage: Sendable, Codable, Hashable {
    public let name: String
    public let kind: String

    public init(name: String, kind: String) {
        self.name = name
        self.kind = kind
    }
}

/// One post-install setup step. `kind` selects which of the optional fields are
/// meaningful: service→`service`, open→`url`, reveal→`path`, command→`run`
/// (always `external:true` per the contract — the app never auto-runs shell),
/// note→`text`. All non-`kind` fields are optional so any step shape parses.
public struct SetupStep: Sendable, Codable, Hashable {
    public let kind: String
    public let service: String?
    public let label: String?
    public let url: String?
    public let path: String?
    public let run: String?
    public let external: Bool?
    public let text: String?

    public init(kind: String, service: String? = nil, label: String? = nil,
                url: String? = nil, path: String? = nil, run: String? = nil,
                external: Bool? = nil, text: String? = nil) {
        self.kind = kind
        self.service = service
        self.label = label
        self.url = url
        self.path = path
        self.run = run
        self.external = external
        self.text = text
    }
}

/// A "further reading" link on a bundle.
public struct BundleLink: Sendable, Codable, Hashable {
    public let label: String
    public let url: String

    public init(label: String, url: String) {
        self.label = label
        self.url = url
    }
}

// MARK: - Lossy decoding

/// Decodes `T` but captures any decode error instead of throwing, so it can be
/// used inside `[Throwable<T>]` to decode an array element-by-element where bad
/// elements are dropped rather than failing the whole array. (A directly-thrown
/// element decode does not advance `JSONDecoder`'s unkeyed container, so the
/// error must be caught at the element boundary — this wrapper does exactly that.)
struct Throwable<T: Decodable>: Decodable {
    let result: Result<T, Error>
    init(from decoder: Decoder) throws {
        result = Result(catching: { try T(from: decoder) })
    }
}

/// On-disk `bundles.json` shape: `{ schemaVersion, generatedAt?, bundles: [...] }`.
/// `schemaVersion`/`generatedAt` are optional (the generator omits the timestamp
/// for deterministic diffs); each bundle is wrapped in `Throwable` so a single
/// malformed recipe is skipped, not fatal.
private struct BundleFile: Decodable {
    let schemaVersion: Int?
    let bundles: [Throwable<BrewBundle>]
}

/// Locale overlay for user-facing bundle prose. Mirrors the Tauri
/// `bundles.ru.json` shape and leaves recipe IDs, package tokens, commands, and
/// URLs untouched.
private struct BundleLocaleFile: Decodable {
    let locale: String?
    let bundles: [BundleLocalePatch]
}

private struct BundleLocalePatch: Decodable {
    let id: String
    let name: String?
    let tagline: String?
    let description: String?
    let capabilityNotes: [String: String]?
    let setup: [SetupStepLocalePatch]?
    let caveats: String?
    let links: [BundleLinkLocalePatch]?
}

private struct SetupStepLocalePatch: Decodable {
    let index: Int
    let label: String?
    let text: String?
}

private struct BundleLinkLocalePatch: Decodable {
    let url: String
    let label: String?
}

// MARK: - Loader

/// Parses the bundled `bundles.json` into `[Bundle]`, tolerantly. A Sendable
/// value type (mirrors the `CategoryCatalog`/`EnrichmentCatalog` bundled-data
/// loaders); call `load()` off the main thread from `AppModel.loadBundledData()`.
public struct BundleCatalog: Sendable {
    /// The `bundles.json` `schemaVersion` this build understands. A live payload
    /// with a NEWER schema is refused (the app keeps its bundled copy) rather
    /// than risk mis-parsing a format it doesn't know — fail-soft forward-compat.
    static let supportedSchemaVersion = 1

    public init() {}

    /// Decode the bundled catalog. Returns `[]` if the resource is missing or
    /// the top-level JSON is malformed; individual malformed recipes are simply
    /// dropped so the remaining valid bundles still load. Preserves file order.
    public func load(locale: String? = nil) -> [BrewBundle] {
        guard let url = Bundle.module.url(forResource: "bundles", withExtension: "json"),
              let data = try? Data(contentsOf: url) else {
            return []
        }
        return Self.localized(Self.parse(data), locale: locale)
    }

    /// Decode bundles from raw JSON bytes (the testable core of `load()`).
    /// Skips recipes that fail to decode; returns `[]` on a malformed top level.
    static func parse(_ data: Data) -> [BrewBundle] {
        guard let file = try? JSONDecoder().decode(BundleFile.self, from: data) else {
            return []
        }
        return file.bundles.compactMap { try? $0.result.get() }
    }

    /// Parse a LIVE-fetched payload (M5). Distinct from `parse` in that it can
    /// say "don't use this" by returning `nil`, so the caller keeps the bundled
    /// copy: `nil` when the top-level JSON is malformed OR its `schemaVersion` is
    /// newer than `supportedSchemaVersion`. Otherwise it lossily decodes the
    /// recipes (skipping malformed ones), same as `parse`. A missing
    /// `schemaVersion` is treated as compatible.
    static func parseLive(_ data: Data) -> [BrewBundle]? {
        guard let file = try? JSONDecoder().decode(BundleFile.self, from: data) else {
            return nil
        }
        if let version = file.schemaVersion, version > supportedSchemaVersion {
            return nil
        }
        return file.bundles.compactMap { try? $0.result.get() }
    }

    static func localized(_ bundles: [BrewBundle], locale: String?) -> [BrewBundle] {
        let normalized = normalizeLocale(locale)
        guard normalized == "ru",
              let url = Bundle.module.url(forResource: "bundles.ru", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let overlay = try? JSONDecoder().decode(BundleLocaleFile.self, from: data),
              normalizeLocale(overlay.locale) == normalized
        else {
            return bundles
        }
        return localized(bundles, locale: normalized, overlayData: data)
    }

    static func localized(_ bundles: [BrewBundle], locale: String?, overlayData data: Data) -> [BrewBundle] {
        let normalized = normalizeLocale(locale)
        guard normalized == "ru",
              let overlay = try? JSONDecoder().decode(BundleLocaleFile.self, from: data),
              normalizeLocale(overlay.locale) == normalized
        else {
            return bundles
        }
        var patches: [String: BundleLocalePatch] = [:]
        for patch in overlay.bundles where !patch.id.isEmpty {
            patches[patch.id] = patch
        }
        return bundles.map { bundle in
            guard let patch = patches[bundle.id] else { return bundle }
            return localized(bundle, with: patch)
        }
    }

    private static func localized(_ bundle: BrewBundle, with patch: BundleLocalePatch) -> BrewBundle {
        var notes = bundle.capabilityNotes ?? [:]
        for (key, value) in patch.capabilityNotes ?? [:] where !key.isEmpty && !value.isEmpty {
            notes[key] = value
        }
        let localizedSetup = localizedSetup(bundle.setup, patches: patch.setup ?? [])
        let localizedLinks = localizedLinks(bundle.links, patches: patch.links ?? [])
        return BrewBundle(
            id: bundle.id,
            name: patch.name.nonEmpty ?? bundle.name,
            tagline: patch.tagline.nonEmpty ?? bundle.tagline,
            description: patch.description.nonEmpty ?? bundle.description,
            category: bundle.category,
            icon: bundle.icon,
            packages: bundle.packages,
            tap: bundle.tap,
            requires: bundle.requires,
            capabilityNotes: notes,
            setup: localizedSetup,
            caveats: patch.caveats.nonEmpty ?? bundle.caveats,
            links: localizedLinks,
            maintainer: bundle.maintainer,
            addedIn: bundle.addedIn
        )
    }

    private static func localizedSetup(_ setup: [SetupStep]?, patches: [SetupStepLocalePatch]) -> [SetupStep]? {
        guard var setup else { return nil }
        for patch in patches where setup.indices.contains(patch.index) {
            let old = setup[patch.index]
            setup[patch.index] = SetupStep(
                kind: old.kind,
                service: old.service,
                label: patch.label.nonEmpty ?? old.label,
                url: old.url,
                path: old.path,
                run: old.run,
                external: old.external,
                text: patch.text.nonEmpty ?? old.text
            )
        }
        return setup
    }

    private static func localizedLinks(_ links: [BundleLink]?, patches: [BundleLinkLocalePatch]) -> [BundleLink]? {
        guard var links else { return nil }
        for patch in patches {
            guard let label = patch.label.nonEmpty,
                  let idx = links.firstIndex(where: { $0.url == patch.url })
            else { continue }
            let old = links[idx]
            links[idx] = BundleLink(label: label, url: old.url)
        }
        return links
    }

    fileprivate static func normalizeLocale(_ locale: String?) -> String {
        guard let locale else { return "en" }
        let lc = locale.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
        return lc == "ru" || lc.hasPrefix("ru-") || lc.hasPrefix("ru_") ? "ru" : "en"
    }
}

private extension Optional where Wrapped == String {
    var nonEmpty: String? {
        guard let value = self?.trimmingCharacters(in: .whitespacesAndNewlines), !value.isEmpty else {
            return nil
        }
        return value
    }
}

/// Opt-in live fetch for the Bundles catalog (M5) — the native mirror of the
/// enrichment/trending live clients (`EnrichmentLiveService`,
/// `TrendingHistoryService`): an actor, soft-fail everywhere, pure transport.
/// The caller (`AppModel`) gates on `settings.liveBundlesAllowed` (opt-in +
/// network) before invoking. The base host is the same first-party serving
/// domain the enrichment/trending clients use (already in committed source);
/// only the `/bundles/` path differs. Injectable `baseURL`/`session` keep it
/// testable and keep the host out of any hardcoded string beyond this default.
public actor BundleLiveService {
    private let baseURL: URL
    private let session: URLSession

    public init(
        baseURL: URL = URL(string: "https://brew-browser.zerologic.com/bundles/")!,
        session: URLSession? = nil
    ) {
        self.baseURL = baseURL
        if let session {
            self.session = session
        } else {
            let config = URLSessionConfiguration.ephemeral
            config.timeoutIntervalForRequest = 8
            config.timeoutIntervalForResource = 15
            self.session = URLSession(configuration: config)
        }
    }

    /// GET `bundles/bundles.json` → tolerant `[BrewBundle]`. Returns `nil` on any
    /// failure (offline, 404 — the endpoint may not exist yet, network error,
    /// malformed JSON, or a newer-than-supported schema) so the caller keeps the
    /// bundled copy.
    func fetchBundles(locale: String? = nil) async -> [BrewBundle]? {
        let url = baseURL.appendingPathComponent("bundles.json", isDirectory: false)
        guard let data = await fetchData(url) else { return nil }
        guard let bundles = BundleCatalog.parseLive(data) else { return nil }
        let normalized = BundleCatalog.normalizeLocale(locale)
        guard normalized != "en" else { return bundles }
        let overlayURL = baseURL.appendingPathComponent("bundles.\(normalized).json", isDirectory: false)
        guard let overlayData = await fetchData(overlayURL) else { return bundles }
        return BundleCatalog.localized(bundles, locale: normalized, overlayData: overlayData)
    }

    private func fetchData(_ url: URL) async -> Data? {
        do {
            let (data, response) = try await session.data(from: url)
            if let http = response as? HTTPURLResponse, !(200...299).contains(http.statusCode) {
                return nil
            }
            return data
        } catch {
            return nil
        }
    }
}
